version: '3'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/calculadora_defensivos?schema=public
      - NODE_ENV=development
      - PORT=3333
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calculadora_defensivos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


