services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "5555:5555" # Prisma Studio local
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/calculadora_defensivos?schema=public
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD} # Usará sua senha complexa
      - POSTGRES_DB=calculadora_defensivos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: