services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/calculadora_defensivos?schema=public
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - db
    command: npm run start

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calculadora_defensivos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
